### PR TITLE
forward compatibility with new engine

### PR DESCRIPTION
**Pull request by gajop**

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
Thanks! Unfortunately Real Life is getting in the way ATM (trying to survive financially) so I haven't been giving Evo the constant attention that it had been getting for the past year. That will ofc change soon, but I have to make sure that I'm not about to wind up homeless first.

**Comment by gajop** [comment]
No worries. I was just trying to get it ported to a newer version so I can use it (and SB) with Chobby.

**Comment by ForbodingAngel** [comment]
Thanks, I really appreciate it. I'm trying to get RL sorted out, which is why my progress has been sluggish. I started whining to you about SB at a time when I didn't have much time for evo (didn't realize it at the time... things started falling apart a day or two after). Which is weird considering that evo has been like a 40 hr a week job for the past year, but stuff in RL got bad enough that I have to deal with that. Hopefully only a week or so more :-)

**Comment by gajop** [comment]
I understand that very well. I've only just returned to slightly higher activity in Spring after a long absence. I think I'll be able to consistently put in more hours, at least for the next year.
I haven't yet gotten to the dialog request you asked for, and as it turns out it's a bit more complicated than I thought, unless I want to just hack it in. Right now I'm focusing on a few key things I think are important for Spring, so it might take a bit more time until I can get back to it.

**Pull request merged**
