### PR TITLE
Global buildlist (with example)

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
This is exactly what I have wanted since forever. I thought it wasn't possible. I am very happy to be wrong. Thank you! :-)

**Comment by sprunk** [comment]
Looking at the defs there's a lot more potential for pre- and post- processing.

**Comment by ForbodingAngel** [comment]
I would tend to agree. Before I do that I need to move to an alldefs post system which means porting over the current stuff. Not hard, just time consuming. This so I can access pre for unit and weapons in the same place.

**Comment by ForbodingAngel** [comment]
I meant post*

Typing on phone and got mixed up.

**Comment by sprunk** [comment]
"Alldefs post system"?

**Comment by sprunk** [comment]
You can already access both unit- and weapon- defs from the same place (that place being weapondefs post).

**Comment by ForbodingAngel** [comment]
You can? Without any special loading?

I was referring to this type of system: https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/gamedata/alldefs_post.lua

**Comment by sprunk** [comment]
That file does not do any special loading and is not even needed for BA's use case.

**Comment by ForbodingAngel** [comment]
Yes, I know, but I figured by linking to it you would follow it to unit and weapon defs post and see what was happening there.

**Comment by sprunk** [comment]
I've seen those and nothing special happens there either.

What do you want to do, that you think would require adding alldefs post?

**Comment by ForbodingAngel** [comment]
Sorry for the late reply here, I've been really busy. Well, I hadn't looked in depth at them myself to see how it worked, and I did not know that weapondefs post had that kind of access.

That said, I like the way it is set up there and I want to replicate it. Which means I need to move my existing stuff over to it while tossing out the things I no longer actively use.

That would allow me to do the energycost to fire calculations in one place, same for shields recharge. It would also allow me to do some cool calculations for weapons, perhaps factoring in range and refire rate as well as damage and aoe.

For a while I've dreamed about having a system of managing various costs automatically. I've done this with buildings cost and HP, for example. So yes, i need to do it, but I've been messing with bigger fish lately so I just haven't done it yet.

**Comment by sprunk** [comment]
Technically you can do all that in regular posts. But if you want to pile everything up in one file then sure.

**Pull request merged**
