### PR TITLE
Fixed missing licenses

### LINKED ISSUE #94: License could be more clear
> All assets are CC BY SA except where otherwise marked (Most LUA falls under GPL, for example).

This leaves you as a person trying to integrate this into a GNU system as a package with more questions than answers. Most of the lua files I looked at didn't have an license header or any kind of license statement.
To avoid confusion on system level I'd suggest that you specificy the license more explicitly, for example like 0ad does, or like mediagoblin (https://git.savannah.gnu.org/cgit/mediagoblin.git/tree/COPYING).

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes #94 properly.

TL;DR 
> You should have received a copy of the GNU General Public License along with this program;

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
The difference is that this is not a program. This is a collection of files that when added to the spring engine results in spring running it as a game.

There isn't anything homogeneous in the licenses, as you will see from the headers. A lot of them were written by people who didn't really care, which is why you will see license texts of "Whatever you want 2019" and public domain, etc.

The vast majority of lua content is covered by the engine license, lgpl. The art is a different story and is covered by a CC license. This is why license.txt denotes "where otherwise marked".

**Comment by Mailaender** [comment]
I understand. However, you are forced to ship the license text. It is (in theory) a GPL violation otherwise. My current goal is not to sue you, though. I am trying to update https://software.opensuse.org/package/springrts-evolution-rts as you seem to ship the game for Windows only at the moment.

**Comment by ForbodingAngel** [comment]
That package was not added by me. Evo is only distributed via itch. Any other distribution method has been added via a 3rd party. I guarantee you that whatever is in that repo will not run with any spring version released within that past few years. I wouldn't be surprised if that package is nearly a decade old.

The engine ships all relevant license texts and evo isn't "officially" distributed without the engine. You can see for yourself over at https://forboding-angel.itch.io/evolution-rts

I don't explicitly have a problem with including specific license texts, but I feel that you're probably barking up the wrong tree here. Perhaps this is more akin to what you're looking for? https://github.com/spring/spring/blob/develop/LICENSE

This repo if archived, won't do anything. There aren't any executable binaries or anything to run the game. This is just content for the spring engine to execute.

Let me know if I'm missing something here. I'm not trying to be difficult.

**Comment by Mailaender** [comment]
It doesn't matter if you are engine or scripting gameplay with Lua. The GPL works the same way. Notice how the Spring engine also ships the GPL in full text. I saw https://forboding-angel.itch.io/evolution-rts but sadly it is Windows only. If you need help packaging it for Linux using @AppImage or similar, maybe I can help.

**Pull request merged**
